####################
# ASCOT5 Build Stage
####################
# TODO should probably move away from using submodules. It means the version
# information of dependencies is scattered, and it would be better to centralise
# it here.
ARG MOOSE_BASE=moose-ubuntu-dev MOOSE_VER=2021-09-15 USER=dev
FROM ${MOOSE_BASE}:${MOOSE_VER} AS ascot5-moose-ubuntu

# Basic environment
ARG USER
WORKDIR $HOME
# Set path to shared library for Python interface to use and other environment
ENV LD_LIBRARY_PATH=$HOME/ascot5 EDITOR=vim PATH="${HOME}/.local/bin:${PATH}"

# ASCOT5 main C program and library
COPY ascot5 ascot5
RUN sudo apt-get update && sudo apt-get -y install make libhdf5-dev && \
    sudo chown -R ${USER}:${USER} ascot5
# This is a completely serial version with no MPI or OpenMP offloading to GPUs
ENV MAKE_OPT='NOGIT=true CC=h5cc MPI=0 FLAGS=-foffload=disable'
RUN cd ascot5 && make clean ${MAKE_OPT} && make ascot5_main ${MAKE_OPT} && \
    make libascot ${MAKE_OPT} && \
    sudo ln -s -t /usr/local/bin/ $(readlink -f ascot5_main)

# ASCOT5 Python
RUN sudo apt-get -y install python3-pip 
COPY ascot5-python ascot5/ascot5-python
RUN sudo chown -R $USER:$USER ascot5/ascot5-python && python -m pip install -e ascot5/ascot5-python/a5py

###################################
# Phaethon Dependencies Build Stage
###################################
FROM ascot5-moose-ubuntu AS phaethon-deps

# TODO put a requirements.txt file in repo instead of listing these here
RUN python -m pip install --upgrade meshio[all] click

##################################
# Phaethon Development Environment
##################################
FROM phaethon-deps as phaethon-dev

# Some development utilities, including git-lfs
RUN sudo apt-get -y install clang-format curl hdf5-tools gdb
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash && \
    sudo apt-get -y install git-lfs && \
    git lfs install

# Python dev deps
RUN python -m pip install --upgrade flake8 jupyter

##############################
# Phaethon Release Build Stage
##############################
FROM phaethon-deps as phaethon

ARG USER
WORKDIR $HOME/phaethon
COPY ./ ./
    
RUN sudo chown -R ${USER}:${USER} . && git clean -dfx \
    && make -j4 && make -C unit/ -j4 
RUN ./run_tests && cd unit && ./run_tests
