FROM ubuntu:20.04 AS moose-ubuntu-dev

# Basic environment
ARG MOOSE_VER=2021-09-15 DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C.UTF-8 LANG=C.UTF-8 METHOD=devel
RUN apt-get update && apt-get -y install \
    cmake \
    gcc \
    g++ \
    gfortran \
    git \
    libopenmpi3 \
    python3 \
    python3-dev \
    python3-distutils \
    python3-pip \
    python-is-python3 \
    wget

# Add a non-root user so git works inside the dev container
ARG USERNAME=dev
ARG USER_UID=1002
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
USER dev
ENV HOME=/home/${USERNAME}

# PETSC dependencies
RUN sudo apt-get -y install \
    bison \
    flex \
    libblas-dev \
    liblapack-dev

# MPI environment variables
ENV CC=mpicc CXX=mpicxx F90=mpif90 F77=mpif77 FC=mpif90

# Get MOOSE source code
WORKDIR $HOME
RUN git clone https://github.com/idaholab/moose.git && \
    cd moose && \
    git checkout $MOOSE_VER
ENV MOOSE_JOBS=4
WORKDIR $HOME/moose

# Make PETSC
RUN ./scripts/update_and_rebuild_petsc.sh --prefix=$HOME/petsc
ENV PETSC_DIR=$HOME/petsc

# Make libMesh
RUN ./scripts/update_and_rebuild_libmesh.sh --with-mpi

# Make MOOSE framework
RUN ./configure --with-derivative-size=200 --with-ad-indexing-type=global && \
    cd test && \
    make -j4 && \
    ./run_tests -j 4
ENV MOOSE_DIR=$HOME/moose

# Make MOOSE modules
RUN cd modules && \
    make -j4  && \
    ./run_tests -j 4
